name: Build and Copy to New Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create New Branch
        run: |
          git checkout -b compiled-code
          git add dist/
          git commit -m "Compiled code"

          # Add the following line to use the access token from secrets
          git push https://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@github.com/Pavanpatil0744/medusa_backend.git compiled-code
