# .github/workflows/build.yml
name: Build Medusa Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      # Add the steps to create and push to the new branch 'branch2'
      - name: Create New Branch
        run: git checkout -b branch2

      - name: Copy Build Files
        run: |
          mkdir -p build
          cp -R dist/* build/


