# .github/workflows/build.yml
name: Build Medusa Project and Push to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      # Add the steps to create and push to the new branch 'branch2'
      - name: Create New Branch
        run: git checkout -b branch2

      - name: Copy Build Files
        run: |
          mkdir -p build
          cp -R dist/* build/
      # Install and configure AWS CLI
      - name: Configure AWS CLI
        run: |
          npm install -g aws-cli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1
      # Upload build files to S3 bucket
      - name: Push to S3 Bucket
        run: |
          aws s3 sync build/ s3://medusa-backend/ --delete
      # Continue with the rest of the workflow,
