name: Build and Copy to New Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Create New Branch
        run: |
          git checkout -b compiled-code
          git add dist/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Compiled code"
          git push origin compiled-code
